/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bean.CodeSql;
import bean.Vehicle;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import util.DBUtility;
import java.sql.*;
import javax.swing.*;


public class Warehouse extends javax.swing.JInternalFrame {

 public static Connection conn = DBUtility.getConnection();
    String imagePath = "src/images/none.jpg";

    ArrayList<Vehicle> lsvhc = new ArrayList<>();
    ArrayList<String> listCombReceiptNote = new ArrayList<>();
    ArrayList<String> listCombName = new ArrayList<>();
    ArrayList<String> listCombModel = new ArrayList<>();
    int[] arraySreach = new int[9];
    ImageIcon icon;
    String imageLocation = "d:\\pictures\\car\\";
    String imageName;

    public Warehouse() {
        initComponents();

        icon = new ImageIcon("d:\\pictures\\car\\" + imagePath);

        labelHinhAnh.setIcon(icon);
        labelHinhAnh.setSize(100, 100);

        textSearch.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void removeUpdate(DocumentEvent e) {
                //System.out.println("removeUpdate");
                buttonTimKiemActionPerformed(null);
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                //System.out.println("insertUpdate");
                buttonTimKiemActionPerformed(null);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                //System.out.println("changedUpdate");
                buttonTimKiemActionPerformed(null);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSanPham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        textSearch = new javax.swing.JTextField();
        buttonTimKiem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelHinhAnh = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/images/none.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        labelHinhAnh = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnChangeImage = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        spinWarrantyPeriod = new javax.swing.JSpinner();
        btnRepair = new javax.swing.JButton();
        checkMaLinhKien = new javax.swing.JCheckBox();
        checkTenLinhKien = new javax.swing.JCheckBox();
        checkThoiGianBaoHanh = new javax.swing.JCheckBox();
        checkSoLuongTon = new javax.swing.JCheckBox();
        checkMoTa = new javax.swing.JCheckBox();
        checkAll = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        combReceiptNote = new javax.swing.JComboBox();
        combModel = new javax.swing.JComboBox();
        spinQuantityinStock = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Sản phẩm");
        setName("WareHouse"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 700));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Receipt Note", "Name", "Model", "Quantity in Stock", "WarrantyPeriod", "Description", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSanPham.setPreferredSize(new java.awt.Dimension(525, 32));
        tableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSanPhamMouseClicked(evt);
            }
        });
        tableSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableSanPham);

        jLabel1.setText("Search");

        textSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textSearchKeyPressed(evt);
            }
        });

        buttonTimKiem.setText("Search");
        buttonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTimKiemActionPerformed(evt);
            }
        });

        jLabel2.setText("Follow");

        labelHinhAnh.setMaximumSize(new java.awt.Dimension(300, 202));
        labelHinhAnh.setMinimumSize(new java.awt.Dimension(300, 202));

        javax.swing.GroupLayout panelHinhAnhLayout = new javax.swing.GroupLayout(panelHinhAnh);
        panelHinhAnh.setLayout(panelHinhAnhLayout);
        panelHinhAnhLayout.setHorizontalGroup(
            panelHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );
        panelHinhAnhLayout.setVerticalGroup(
            panelHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHinhAnhLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setText("Model");

        jLabel5.setText("Name Car");

        jLabel7.setText("Warranty Period");

        jLabel8.setText("Quantity in Stock");

        jLabel9.setText("Description");

        textName.setEnabled(false);

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setEnabled(false);
        jScrollPane2.setViewportView(txtDescription);

        btnChangeImage.setText("Change Image");
        btnChangeImage.setEnabled(false);
        btnChangeImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeImageActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnChange.setText("Change");
        btnChange.setActionCommand("Sua");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.setActionCommand("Them");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel10.setText("month");

        spinWarrantyPeriod.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        spinWarrantyPeriod.setEnabled(false);

        btnRepair.setText("Repair");
        btnRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairActionPerformed(evt);
            }
        });

        checkMaLinhKien.setText("Model");
        checkMaLinhKien.setName("1"); // NOI18N
        checkMaLinhKien.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });
        checkMaLinhKien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });

        checkTenLinhKien.setText("Name");
        checkTenLinhKien.setName("2"); // NOI18N
        checkTenLinhKien.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });
        checkTenLinhKien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });

        checkThoiGianBaoHanh.setText("Warranty Period");
        checkThoiGianBaoHanh.setName("5"); // NOI18N
        checkThoiGianBaoHanh.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });
        checkThoiGianBaoHanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });

        checkSoLuongTon.setText("Quantity in Stock");
        checkSoLuongTon.setName("6"); // NOI18N
        checkSoLuongTon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });
        checkSoLuongTon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });
        checkSoLuongTon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSoLuongTonActionPerformed(evt);
            }
        });

        checkMoTa.setText("Description");
        checkMoTa.setName("7"); // NOI18N
        checkMoTa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });
        checkMoTa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });

        checkAll.setText("Search ALL");
        checkAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkAllMouseClicked(evt);
            }
        });
        checkAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAllActionPerformed(evt);
            }
        });

        jLabel11.setText("Receipt Note");

        combReceiptNote.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        combReceiptNote.setEnabled(false);
        combReceiptNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combReceiptNoteMouseClicked(evt);
            }
        });

        combModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        combModel.setEnabled(false);

        spinQuantityinStock.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        spinQuantityinStock.setForeground(new java.awt.Color(0, 0, 204));
        spinQuantityinStock.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(70, 70, 70)
                                .addComponent(checkMaLinhKien)
                                .addGap(86, 86, 86)
                                .addComponent(checkTenLinhKien)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(checkThoiGianBaoHanh)
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkAll)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkMoTa)
                                .addGap(56, 56, 56)
                                .addComponent(btnRepair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(checkSoLuongTon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(panelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(combReceiptNote, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combModel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnChangeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spinWarrantyPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spinQuantityinStock, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(combReceiptNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChangeImage))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(spinWarrantyPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btnChange)
                            .addComponent(spinQuantityinStock))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonTimKiem)
                                .addComponent(checkAll)
                                .addComponent(checkMoTa)
                                .addComponent(btnRepair)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(checkMaLinhKien)
                            .addComponent(checkTenLinhKien)
                            .addComponent(checkThoiGianBaoHanh)
                            .addComponent(checkSoLuongTon))))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("WareHouse");

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void displayData(ResultSet rs) {

        lsvhc.clear();
        DefaultTableModel model;
        model = (DefaultTableModel) tableSanPham.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            while (rs.next()) {
                 Vehicle item = new Vehicle(rs.getString("ReceiptNote"),
                                                    (rs.getString("Name")),
                                                    (rs.getString("Model")),
                                                    (rs.getInt("QuantityinStock")),
                                                    (rs.getInt("WarrantyPeriod")),
                                                    (rs.getString("Description")),
                                                    (rs.getString("Image")));
                    lsvhc.add(item);

                Vector vector = new Vector();

                vector.add(item.getReceiptNote());
                vector.add(item.getName());
                vector.add(item.getModel());
                vector.add(item.getWarrantyPeriod());
                vector.add(item.getQuantityinStock());
                vector.add(item.getDescription());
                model.addRow(vector);

            }
        } catch (Exception ex) {
            System.out.printf("[Ngoại lệ displayData] " + ex.getMessage());
        }
        System.out.println("Rows loaded: " + lsvhc.toArray().length);
    }

    private void loadComboMaPhieuNhap() {
        listCombReceiptNote.clear();
    
        combReceiptNote.removeAllItems();
      
    }

    private void loadCombMaLinhKien() {
        String maphieunhap = combReceiptNote.getSelectedItem().toString();
        if (maphieunhap == null || "".equals(maphieunhap)) {

        }
        listCombModel.clear();
        combModel.removeAllItems();
        
    }

    private void setLabelImage(String imagePath) {
        if (imagePath == null) {
            imagePath = "d:\\pictures\\laptop\\default.jpg";
        }
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imagePath));
        } catch (IOException e) {
        }
        icon = new ImageIcon(img);

        labelHinhAnh.setIcon(icon);
    }

    private void setLabelImage(String imageLocation, String imageName) {
        if (imageName == null) {
            imageName = "default.jpg";
        }
        imageLocation = this.imageLocation;
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imageLocation + imageName));
        } catch (IOException e) {
        }
        icon = new ImageIcon(img);

        labelHinhAnh.setIcon(icon);
    }
    private void btnRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairActionPerformed
        // TODO add your handling code here:
        CodeSql BSP = new CodeSql();
        ResultSet rs = BSP.getAll();
        loadComboMaPhieuNhap();
        loadCombMaLinhKien();

        displayData(rs);
    }//GEN-LAST:event_btnRepairActionPerformed

    private void tableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSanPhamMouseClicked
        int index = tableSanPham.getSelectedRow();
        // loadComboMaPhieuNhap();
        combReceiptNote.setSelectedItem(lsvhc.get(index).getReceiptNote());
        loadCombMaLinhKien();
        combModel.setSelectedIndex(listCombModel.indexOf(lsvhc.get(index).getModel()));

        textName.setText(lsvhc.get(index).getName());
        spinQuantityinStock.setText("" + lsvhc.get(index).getQuantityinStock());
        txtDescription.setText(lsvhc.get(index).getDescription());

        imagePath = lsvhc.get(index).getImage();
        if (imagePath == null) {
            setLabelImage("imageLocspinQuantityinStockt.jpg");
        } else if (imagePath.indexOf("\\") < 0) {
            setLabelImage(imageLocation, imagePath);
        } else {
            setLabelImage(imagePath);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tableSanPhamMouseClicked

    private void btnChangeImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeImageActionPerformed
        // TODO add your handling code here:
//        //Create a file chooser
        final JFileChooser fc = new JFileChooser();
//        //In response to a button click:
//    int returnVal = fc.showOpenDialog(this);
//    
        if (evt.getSource() == btnChangeImage) {
            int returnVal = fc.showOpenDialog(this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                imagePath = file.getPath();
                setLabelImage(imagePath);
                //This is where a real application would open the file.
                //log.append("Opening: " + file.getName() + "." + newline);
            } else {
                // log.append("Open command cancelled by user." + newline);
            }
        }
    }//GEN-LAST:event_btnChangeImageActionPerformed

    private void buttonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTimKiemActionPerformed
        // TODO add your handling code here:
        CodeSql BSP = new CodeSql();
        ResultSet rs = BSP.searchByProperties(arraySreach, textSearch.getText());
        displayData(rs);
    }//GEN-LAST:event_buttonTimKiemActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (btnAdd.getActionCommand().equals("Add")) {
            combModel.setEnabled(true);
            combReceiptNote.setEnabled(true);

            txtDescription.setEnabled(true);
            textName.setEnabled(true);

            spinWarrantyPeriod.setEnabled(true);

            btnChangeImage.setEnabled(true);
            btnSave.setEnabled(true);
            btnChange.setEnabled(false);
            btnAdd.setActionCommand("Detroy");
            btnAdd.setText("Detroy");

            //---
            loadComboMaPhieuNhap();
            loadCombMaLinhKien();

        } else {
            combModel.setEnabled(false);
            combReceiptNote.setEnabled(false);
            txtDescription.setEnabled(false);
            textName.setEnabled(false);
            spinWarrantyPeriod.setEnabled(false);
            btnChangeImage.setEnabled(false);
            btnSave.setEnabled(false);
            btnChange.setEnabled(true);
            btnAdd.setActionCommand("Add");
            btnAdd.setText("Add");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int index = tableSanPham.getSelectedRow();
        //Chua insert dc du lieu

      
        btnAdd.setEnabled(true);
        btnChange.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void checkAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkAllMouseClicked
        // TODO add your handling code here:
        if (checkAll.isSelected()) {
            checkMaLinhKien.setSelected(true);
            checkTenLinhKien.setSelected(true);
            checkMoTa.setSelected(true);
            checkSoLuongTon.setSelected(true);
            checkThoiGianBaoHanh.setSelected(true);
        } else {
            checkMaLinhKien.setSelected(false);
            checkTenLinhKien.setSelected(false);
            checkMoTa.setSelected(false);
            checkSoLuongTon.setSelected(false);
            checkThoiGianBaoHanh.setSelected(false);
        }
    }//GEN-LAST:event_checkAllMouseClicked

    private void checkHangSanXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkHangSanXuatMouseClicked
        // TODO add your handling code here:
        int index;
        JCheckBox check = (JCheckBox) evt.getSource();
        index = Integer.valueOf(check.getName());
        if (check.isSelected()) {
            arraySreach[index] = 1;
        } else {
            arraySreach[index] = 0;
        }
    }//GEN-LAST:event_checkHangSanXuatMouseClicked

    private void checkHangSanXuatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkHangSanXuatStateChanged
        // TODO add your handling code here:
        int index;
        JCheckBox check = (JCheckBox) evt.getSource();
        index = Integer.valueOf(check.getName());
        if (check.isSelected()) {
            arraySreach[index] = 1;
        } else {
            arraySreach[index] = 0;
        }
    }//GEN-LAST:event_checkHangSanXuatStateChanged

    private void textSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonTimKiemActionPerformed(null);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_textSearchKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            btnRepairActionPerformed(null);
        }
    }//GEN-LAST:event_formKeyPressed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        if (btnChange.getActionCommand().equals("Sua")) {
            combModel.setEnabled(true);
            combReceiptNote.setEnabled(true);
            txtDescription.setEnabled(true);
            textName.setEnabled(true);


            btnChangeImage.setEnabled(true);
            btnSave.setEnabled(true);
            btnAdd.setEnabled(false);
            btnChange.setActionCommand("Delete");
            btnChange.setText("Delete");
        } else {
            combModel.setEnabled(false);
            combReceiptNote.setEnabled(false);
            txtDescription.setEnabled(false);
            textName.setEnabled(false);


            btnChangeImage.setEnabled(false);
            btnSave.setEnabled(false);
            btnAdd.setEnabled(true);
            btnChange.setActionCommand("Change");
            btnChange.setText("Change");
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        txtDescription.setText("");
        textName.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void combReceiptNoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combReceiptNoteMouseClicked
        // TODO add your handling code here:
        loadCombMaLinhKien();
    }//GEN-LAST:event_combReceiptNoteMouseClicked

    private void checkSoLuongTonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSoLuongTonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSoLuongTonActionPerformed

    private void checkAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAllActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnChangeImage;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRepair;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton buttonTimKiem;
    private javax.swing.JCheckBox checkAll;
    private javax.swing.JCheckBox checkMaLinhKien;
    private javax.swing.JCheckBox checkMoTa;
    private javax.swing.JCheckBox checkSoLuongTon;
    private javax.swing.JCheckBox checkTenLinhKien;
    private javax.swing.JCheckBox checkThoiGianBaoHanh;
    private javax.swing.JComboBox combModel;
    private javax.swing.JComboBox combReceiptNote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelHinhAnh;
    private javax.swing.JPanel panelHinhAnh;
    private javax.swing.JLabel spinQuantityinStock;
    private javax.swing.JSpinner spinWarrantyPeriod;
    private javax.swing.JTable tableSanPham;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textSearch;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
